language: swift # or objective-c
osx_image: xcode9.3
script:
  - xcodebuild -scheme OpenFlickrClient -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'OpenFlickrClient'
